import type { ActivityInterface } from '@/interfaces/ActivityInterface';

// Estructura tomada del archivo "Tabla de permanencia Provisional.xlsx" (raíz).
// committeeId: null = actividad de la hoja general; con id = actividad propia de ese comité.
export const activitySeeder: ActivityInterface[] = [
  {
    id: 1,
    groupId: 1,
    committeeId: null,
    name: 'Asambleas generales',
    description:
      'Asistir, participar y prestar atención activa a las asambleas generales del grupo, llegando puntual.',
    weight: 20,
    period: '2026-1',
  },
  {
    id: 2,
    groupId: 1,
    committeeId: null,
    name: 'Macroeventos',
    description: 'Participar en cada macroevento cumpliendo las responsabilidades asignadas.',
    weight: 15,
    period: '2026-1',
  },
  {
    id: 3,
    groupId: 1,
    committeeId: null,
    name: 'Integración',
    description: 'Asistir a las integraciones del grupo.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 4,
    groupId: 1,
    committeeId: null,
    name: 'Horas de carpa',
    description: 'Cumplir las horas de carpa especificadas para los eventos del semestre.',
    weight: 10,
    period: '2026-1',
  },
  {
    id: 5,
    groupId: 1,
    committeeId: null,
    name: 'Assessment',
    description: 'Participar activamente en alguno de los roles del proceso de selección.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 6,
    groupId: 1,
    committeeId: 1,
    name: 'Asistencia a reuniones',
    description: 'Asistir a las reuniones semanales del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 7,
    groupId: 1,
    committeeId: 1,
    name: 'Actitud',
    description: 'Actitud y disposición dentro del comité.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 8,
    groupId: 1,
    committeeId: 1,
    name: 'Trabajo en el comité',
    description: 'Cumplimiento del trabajo asignado dentro del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 9,
    groupId: 1,
    committeeId: 2,
    name: 'Asistencia a reuniones',
    description: 'Asistir a las reuniones semanales del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 10,
    groupId: 1,
    committeeId: 2,
    name: 'Actitud',
    description: 'Actitud y disposición dentro del comité.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 11,
    groupId: 1,
    committeeId: 2,
    name: 'Trabajo en el comité',
    description: 'Cumplimiento del trabajo asignado dentro del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 12,
    groupId: 1,
    committeeId: 3,
    name: 'Asistencia a reuniones',
    description: 'Asistir a las reuniones semanales del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 13,
    groupId: 1,
    committeeId: 3,
    name: 'Actitud',
    description: 'Actitud y disposición dentro del comité.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 14,
    groupId: 1,
    committeeId: 3,
    name: 'Trabajo en el comité',
    description: 'Cumplimiento del trabajo asignado dentro del comité (contactos y patrocinios).',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 15,
    groupId: 1,
    committeeId: 4,
    name: 'Asistencia a reuniones',
    description: 'Asistir a las reuniones semanales del comité.',
    weight: 25,
    period: '2026-1',
  },
  {
    id: 16,
    groupId: 1,
    committeeId: 4,
    name: 'Actitud',
    description: 'Actitud y disposición dentro del comité.',
    weight: 5,
    period: '2026-1',
  },
  {
    id: 17,
    groupId: 1,
    committeeId: 4,
    name: 'Trabajo en el comité',
    description: 'Cumplimiento del cronograma de publicaciones y proactividad.',
    weight: 25,
    period: '2026-1',
  },
];
