import type { GroupMemberInterface } from '@/interfaces/GroupMemberInterface';

// Un estado por miembro del grupo demo (groupId 1). Para los miembros que en el Excel
// original tenían varios estados a la vez, se conserva solo el primero listado como
// su estado principal, siguiendo la regla UNIQUE(id_member, id_group) del ER.
export const groupMemberSeeder: GroupMemberInterface[] = [
  { id: 1, memberId: 1, groupId: 1, memberStatusId: 1 },
  { id: 2, memberId: 2, groupId: 1, memberStatusId: 1 },
  { id: 3, memberId: 3, groupId: 1, memberStatusId: 2 },
  { id: 4, memberId: 4, groupId: 1, memberStatusId: 1 },
  { id: 5, memberId: 5, groupId: 1, memberStatusId: 4 },
  { id: 6, memberId: 6, groupId: 1, memberStatusId: 2 },
  { id: 7, memberId: 7, groupId: 1, memberStatusId: 1 },
  { id: 8, memberId: 8, groupId: 1, memberStatusId: 1 },
  { id: 9, memberId: 9, groupId: 1, memberStatusId: 1 },
  { id: 10, memberId: 10, groupId: 1, memberStatusId: 1 },
  { id: 11, memberId: 11, groupId: 1, memberStatusId: 1 },
  { id: 12, memberId: 12, groupId: 1, memberStatusId: 1 },
  { id: 13, memberId: 13, groupId: 1, memberStatusId: 1 },
  { id: 14, memberId: 14, groupId: 1, memberStatusId: 4 },
  { id: 15, memberId: 15, groupId: 1, memberStatusId: 1 },
  { id: 16, memberId: 16, groupId: 1, memberStatusId: 1 },
  { id: 17, memberId: 17, groupId: 1, memberStatusId: 1 },
  { id: 18, memberId: 18, groupId: 1, memberStatusId: 1 },
  { id: 19, memberId: 19, groupId: 1, memberStatusId: 4 },
  { id: 20, memberId: 20, groupId: 1, memberStatusId: 1 },
  { id: 21, memberId: 21, groupId: 1, memberStatusId: 1 },
  { id: 22, memberId: 22, groupId: 1, memberStatusId: 1 },
  { id: 23, memberId: 23, groupId: 1, memberStatusId: 1 },
  { id: 24, memberId: 24, groupId: 1, memberStatusId: 4 },
  { id: 25, memberId: 25, groupId: 1, memberStatusId: 1 },
  { id: 26, memberId: 26, groupId: 1, memberStatusId: 1 },
  { id: 27, memberId: 27, groupId: 1, memberStatusId: 3 },
  { id: 28, memberId: 28, groupId: 1, memberStatusId: 4 },
  { id: 29, memberId: 29, groupId: 1, memberStatusId: 3 },
  { id: 30, memberId: 30, groupId: 1, memberStatusId: 2 },
  { id: 31, memberId: 31, groupId: 1, memberStatusId: 2 },
  { id: 32, memberId: 32, groupId: 1, memberStatusId: 1 },
  { id: 33, memberId: 33, groupId: 1, memberStatusId: 1 },
  { id: 34, memberId: 34, groupId: 1, memberStatusId: 1 },
  { id: 35, memberId: 35, groupId: 1, memberStatusId: 4 },
  { id: 36, memberId: 36, groupId: 1, memberStatusId: 1 },
  { id: 37, memberId: 37, groupId: 1, memberStatusId: 1 },
  { id: 38, memberId: 38, groupId: 1, memberStatusId: 1 },
  { id: 39, memberId: 39, groupId: 1, memberStatusId: 2 },
  { id: 40, memberId: 40, groupId: 1, memberStatusId: 1 },
  { id: 41, memberId: 41, groupId: 1, memberStatusId: 3 },
  { id: 42, memberId: 42, groupId: 1, memberStatusId: 1 },
  { id: 43, memberId: 43, groupId: 1, memberStatusId: 2 },
  { id: 44, memberId: 44, groupId: 1, memberStatusId: 2 },
  { id: 45, memberId: 45, groupId: 1, memberStatusId: 3 },
  { id: 46, memberId: 46, groupId: 1, memberStatusId: 1 },
  { id: 47, memberId: 47, groupId: 1, memberStatusId: 1 },
  { id: 48, memberId: 48, groupId: 1, memberStatusId: 1 },
  { id: 49, memberId: 49, groupId: 1, memberStatusId: 4 },
  { id: 50, memberId: 50, groupId: 1, memberStatusId: 3 },
  { id: 51, memberId: 51, groupId: 1, memberStatusId: 1 },
  { id: 52, memberId: 52, groupId: 1, memberStatusId: 3 },
  { id: 53, memberId: 53, groupId: 1, memberStatusId: 2 },
  { id: 54, memberId: 54, groupId: 1, memberStatusId: 1 },
  { id: 55, memberId: 55, groupId: 1, memberStatusId: 3 },
  { id: 56, memberId: 56, groupId: 1, memberStatusId: 1 },
  { id: 57, memberId: 57, groupId: 1, memberStatusId: 2 },
  { id: 58, memberId: 58, groupId: 1, memberStatusId: 4 },
  { id: 59, memberId: 59, groupId: 1, memberStatusId: 1 },
  { id: 60, memberId: 60, groupId: 1, memberStatusId: 2 },
];
