// Datos de demostración ficticios. Cualquier parecido con personas reales es coincidencia.
import type { MemberInterface } from '@/interfaces/MemberInterface';

export const memberSeeder: MemberInterface[] = [
  {
    id: 1,
    groupId: 1,
    email: 'descobarg1@eafit.edu.co',
    name: 'DANIEL ESCOBAR GONZÁLEZ',
    epikId: '1000533224',
    fullName: 'DANIEL ESCOBAR GONZÁLEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1003999315',
    emailUppercase: 'DESCOBARG1@EAFIT.EDU.CO',
    phone: '3125151125',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 2,
    groupId: 1,
    email: 'sgomezv1@eafit.edu.co',
    name: 'SIMÓN ANTONIA GÓMEZ VÁSQUEZ',
    epikId: '1005708456',
    fullName: 'SIMÓN ANTONIA GÓMEZ VÁSQUEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1037295260',
    emailUppercase: 'SGOMEZV1@EAFIT.EDU.CO',
    phone: '3141736211',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: [],
  },
  {
    id: 3,
    groupId: 1,
    email: 'aisazam1@eafit.edu.co',
    name: 'ALEJANDRO ISAZA MONTOYA',
    epikId: '1007707870',
    fullName: 'ALEJANDRO ISAZA MONTOYA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1071971316',
    emailUppercase: 'AISAZAM1@EAFIT.EDU.CO',
    phone: '3133507767',
    program: 'CONTADURÍA PÚBLICA',
    secondProgram: 'ADMINISTRACIÓN DE NEGOCIOS',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 4,
    groupId: 1,
    email: 'sgonzalezo1@eafit.edu.co',
    name: 'SIMÓN GONZÁLEZ OSPINA',
    epikId: '1006377459',
    fullName: 'SIMÓN GONZÁLEZ OSPINA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1037308985',
    emailUppercase: 'SGONZALEZO1@EAFIT.EDU.CO',
    phone: '3221711401',
    program: 'DISEÑO INTERACTIVO',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 5,
    groupId: 1,
    email: 'svasqueze1@eafit.edu.co',
    name: 'SEBASTIÁN VÁSQUEZ ESCOBAR',
    epikId: '1002741438',
    fullName: 'SEBASTIÁN VÁSQUEZ ESCOBAR',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1062043515',
    emailUppercase: 'SVASQUEZE1@EAFIT.EDU.CO',
    phone: '3201859295',
    program: 'INGENIERÍA DE DISEÑO DE PRODUCTO',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 6,
    groupId: 1,
    email: 'sgiraldoa1@eafit.edu.co',
    name: 'SIMÓN GIRALDO ARISTIZÁBAL',
    epikId: '1003539704',
    fullName: 'SIMÓN GIRALDO ARISTIZÁBAL',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1076125617',
    emailUppercase: 'SGIRALDOA1@EAFIT.EDU.CO',
    phone: '3184470701',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 7,
    groupId: 1,
    email: 'tescobarm1@eafit.edu.co',
    name: 'TOMÁS ALEJANDRA ESCOBAR MONTOYA',
    epikId: '1007187926',
    fullName: 'TOMÁS ALEJANDRA ESCOBAR MONTOYA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1078320463',
    emailUppercase: 'TESCOBARM1@EAFIT.EDU.CO',
    phone: '3207213257',
    program: 'ECONOMÍA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 8,
    groupId: 1,
    email: 'cvelezi1@eafit.edu.co',
    name: 'CAMILA DAVID VÉLEZ ISAZA',
    epikId: '1006402509',
    fullName: 'CAMILA DAVID VÉLEZ ISAZA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1079978790',
    emailUppercase: 'CVELEZI1@EAFIT.EDU.CO',
    phone: '3225641184',
    program: 'BIOLOGÍA',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: [],
  },
  {
    id: 9,
    groupId: 1,
    email: 'cescobarz1@eafit.edu.co',
    name: 'CAMILA ESCOBAR ZAPATA',
    epikId: '1005707197',
    fullName: 'CAMILA ESCOBAR ZAPATA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1014972279',
    emailUppercase: 'CESCOBARZ1@EAFIT.EDU.CO',
    phone: '3178785840',
    program: 'DERECHO',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS', 'PUBLICIDAD'],
  },
  {
    id: 10,
    groupId: 1,
    email: 'shernandezm1@eafit.edu.co',
    name: 'SOFÍA HERNÁNDEZ MORENO',
    epikId: '1008517169',
    fullName: 'SOFÍA HERNÁNDEZ MORENO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1081734598',
    emailUppercase: 'SHERNANDEZM1@EAFIT.EDU.CO',
    phone: '3153394792',
    program: 'INGENIERÍA DE PROCESOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 11,
    groupId: 1,
    email: 'iramirezo1@eafit.edu.co',
    name: 'IGNACIO MARÍA RAMÍREZ OCHOA',
    epikId: '1005159230',
    fullName: 'IGNACIO MARÍA RAMÍREZ OCHOA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1032138745',
    emailUppercase: 'IRAMIREZO1@EAFIT.EDU.CO',
    phone: '3115549169',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 12,
    groupId: 1,
    email: 'jtorresa1@eafit.edu.co',
    name: 'JERÓNIMO TORRES AGUDELO',
    epikId: '1002770370',
    fullName: 'JERÓNIMO TORRES AGUDELO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1035575298',
    emailUppercase: 'JTORRESA1@EAFIT.EDU.CO',
    phone: '3241646352',
    program: 'MERCADEO',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 13,
    groupId: 1,
    email: 'gechavarriad1@eafit.edu.co',
    name: 'GABRIELA MANUELA ECHAVARRÍA DUQUE',
    epikId: '1004159166',
    fullName: 'GABRIELA MANUELA ECHAVARRÍA DUQUE',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1030158366',
    emailUppercase: 'GECHAVARRIAD1@EAFIT.EDU.CO',
    phone: '3117186821',
    program: 'NEGOCIOS INTERNACIONALES',
    secondProgram: 'GEOLOGÍA',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 14,
    groupId: 1,
    email: 'scardonag1@eafit.edu.co',
    name: 'SIMÓN JUAN CARDONA GARCÍA',
    epikId: '1004672073',
    fullName: 'SIMÓN JUAN CARDONA GARCÍA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1089788677',
    emailUppercase: 'SCARDONAG1@EAFIT.EDU.CO',
    phone: '3230302462',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 15,
    groupId: 1,
    email: 'evelezh1@eafit.edu.co',
    name: 'EMMANUEL ANDRÉS VÉLEZ HENAO',
    epikId: '1007835373',
    fullName: 'EMMANUEL ANDRÉS VÉLEZ HENAO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1097854904',
    emailUppercase: 'EVELEZH1@EAFIT.EDU.CO',
    phone: '3114541466',
    program: 'MÚSICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 16,
    groupId: 1,
    email: 'sechavarriat1@eafit.edu.co',
    name: 'SARA JERÓNIMO ECHAVARRÍA TORRES',
    epikId: '1004673212',
    fullName: 'SARA JERÓNIMO ECHAVARRÍA TORRES',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1062092888',
    emailUppercase: 'SECHAVARRIAT1@EAFIT.EDU.CO',
    phone: '3167056907',
    program: 'INGENIERÍA MECÁNICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 17,
    groupId: 1,
    email: 'lmejiav1@eafit.edu.co',
    name: 'LAURA MEJÍA VÁSQUEZ',
    epikId: '1008075854',
    fullName: 'LAURA MEJÍA VÁSQUEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1028688676',
    emailUppercase: 'LMEJIAV1@EAFIT.EDU.CO',
    phone: '3207653432',
    program: 'INGENIERÍA CIVIL',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 18,
    groupId: 1,
    email: 'sbedoyaf1@eafit.edu.co',
    name: 'SAMUEL ALEJANDRA BEDOYA FLÓREZ',
    epikId: '1003652414',
    fullName: 'SAMUEL ALEJANDRA BEDOYA FLÓREZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1007849494',
    emailUppercase: 'SBEDOYAF1@EAFIT.EDU.CO',
    phone: '3245544417',
    program: 'INGENIERÍA CIVIL',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: [],
  },
  {
    id: 19,
    groupId: 1,
    email: 'pgonzalezj1@eafit.edu.co',
    name: 'PAULINA FELIPE GONZÁLEZ JARAMILLO',
    epikId: '1001140194',
    fullName: 'PAULINA FELIPE GONZÁLEZ JARAMILLO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1090625494',
    emailUppercase: 'PGONZALEZJ1@EAFIT.EDU.CO',
    phone: '3163137065',
    program: 'CONTADURÍA PÚBLICA',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 20,
    groupId: 1,
    email: 'egallegod1@eafit.edu.co',
    name: 'EMMANUEL GALLEGO DUQUE',
    epikId: '1004374922',
    fullName: 'EMMANUEL GALLEGO DUQUE',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1027415205',
    emailUppercase: 'EGALLEGOD1@EAFIT.EDU.CO',
    phone: '3184338089',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 21,
    groupId: 1,
    email: 'sgallegoh1@eafit.edu.co',
    name: 'SEBASTIÁN CAROLINA GALLEGO HERNÁNDEZ',
    epikId: '1003576135',
    fullName: 'SEBASTIÁN CAROLINA GALLEGO HERNÁNDEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1067898694',
    emailUppercase: 'SGALLEGOH1@EAFIT.EDU.CO',
    phone: '3171189194',
    program: 'INGENIERÍA DE PROCESOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 22,
    groupId: 1,
    email: 'mmorenol1@eafit.edu.co',
    name: 'MARTÍN MORENO LONDOÑO',
    epikId: '1008874152',
    fullName: 'MARTÍN MORENO LONDOÑO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1001049999',
    emailUppercase: 'MMORENOL1@EAFIT.EDU.CO',
    phone: '3248874917',
    program: 'ADMINISTRACIÓN DE NEGOCIOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 23,
    groupId: 1,
    email: 'aflorezz1@eafit.edu.co',
    name: 'ANDRÉS FLÓREZ ZAPATA',
    epikId: '1003533779',
    fullName: 'ANDRÉS FLÓREZ ZAPATA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1096316277',
    emailUppercase: 'AFLOREZZ1@EAFIT.EDU.CO',
    phone: '3192041226',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 24,
    groupId: 1,
    email: 'lzapatam1@eafit.edu.co',
    name: 'LAURA ZAPATA MARTÍNEZ',
    epikId: '1002194789',
    fullName: 'LAURA ZAPATA MARTÍNEZ',
    documentType: 'Tarjeta de identidad',
    documentNumber: '1085511909',
    emailUppercase: 'LZAPATAM1@EAFIT.EDU.CO',
    phone: '3170318081',
    program: 'INGENIERÍA FÍSICA',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 25,
    groupId: 1,
    email: 'sfloreze1@eafit.edu.co',
    name: 'SEBASTIÁN FLÓREZ ESCOBAR',
    epikId: '1006194416',
    fullName: 'SEBASTIÁN FLÓREZ ESCOBAR',
    documentType: 'Tarjeta de identidad',
    documentNumber: '1078183110',
    emailUppercase: 'SFLOREZE1@EAFIT.EDU.CO',
    phone: '3248317326',
    program: 'INGENIERÍA DE PROCESOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN', 'GESTIÓN HUMANA'],
  },
  {
    id: 26,
    groupId: 1,
    email: 'ihernandezh1@eafit.edu.co',
    name: 'ISABELLA HERNÁNDEZ HENAO',
    epikId: '1006817881',
    fullName: 'ISABELLA HERNÁNDEZ HENAO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1083303777',
    emailUppercase: 'IHERNANDEZH1@EAFIT.EDU.CO',
    phone: '3141487595',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 27,
    groupId: 1,
    email: 'emejiaz1@eafit.edu.co',
    name: 'EMMANUEL MEJÍA ZAPATA',
    epikId: '1001813543',
    fullName: 'EMMANUEL MEJÍA ZAPATA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1051343880',
    emailUppercase: 'EMEJIAZ1@EAFIT.EDU.CO',
    phone: '3110395056',
    program: 'PSICOLOGÍA',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['GESTIÓN HUMANA', 'DIVULGACIÓN'],
  },
  {
    id: 28,
    groupId: 1,
    email: 'maristizabalc1@eafit.edu.co',
    name: 'MARÍA ARISTIZÁBAL CARDONA',
    epikId: '1001164686',
    fullName: 'MARÍA ARISTIZÁBAL CARDONA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1037463522',
    emailUppercase: 'MARISTIZABALC1@EAFIT.EDU.CO',
    phone: '3194260071',
    program: 'DISEÑO INTERACTIVO',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 29,
    groupId: 1,
    email: 'smontoyam1@eafit.edu.co',
    name: 'SOFÍA MONTOYA MARTÍNEZ',
    epikId: '1007290770',
    fullName: 'SOFÍA MONTOYA MARTÍNEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1046397338',
    emailUppercase: 'SMONTOYAM1@EAFIT.EDU.CO',
    phone: '3184202113',
    program: 'DERECHO',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['GESTIÓN HUMANA', 'PUBLICIDAD'],
  },
  {
    id: 30,
    groupId: 1,
    email: 'jgomezd1@eafit.edu.co',
    name: 'JUAN GÓMEZ DUQUE',
    epikId: '1009033725',
    fullName: 'JUAN GÓMEZ DUQUE',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1092188405',
    emailUppercase: 'JGOMEZD1@EAFIT.EDU.CO',
    phone: '3152891215',
    program: 'ECONOMÍA',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 31,
    groupId: 1,
    email: 'gquinterog1@eafit.edu.co',
    name: 'GABRIELA QUINTERO GIRALDO',
    epikId: '1004960271',
    fullName: 'GABRIELA QUINTERO GIRALDO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1074411983',
    emailUppercase: 'GQUINTEROG1@EAFIT.EDU.CO',
    phone: '3134168559',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['RELACIONES PÚBLICAS', 'GESTIÓN HUMANA'],
  },
  {
    id: 32,
    groupId: 1,
    email: 'amorenoa1@eafit.edu.co',
    name: 'ALEJANDRA MORENO ÁLVAREZ',
    epikId: '1009730529',
    fullName: 'ALEJANDRA MORENO ÁLVAREZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1081424737',
    emailUppercase: 'AMORENOA1@EAFIT.EDU.CO',
    phone: '3186503119',
    program: 'COMUNICACIÓN SOCIAL',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 33,
    groupId: 1,
    email: 'lcardonag1@eafit.edu.co',
    name: 'LAURA CAROLINA CARDONA GONZÁLEZ',
    epikId: '1003940441',
    fullName: 'LAURA CAROLINA CARDONA GONZÁLEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1090301106',
    emailUppercase: 'LCARDONAG1@EAFIT.EDU.CO',
    phone: '3183327590',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 34,
    groupId: 1,
    email: 'cgarciap1@eafit.edu.co',
    name: 'CAROLINA GARCÍA POSADA',
    epikId: '1009658155',
    fullName: 'CAROLINA GARCÍA POSADA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1026096655',
    emailUppercase: 'CGARCIAP1@EAFIT.EDU.CO',
    phone: '3203073435',
    program: 'PSICOLOGÍA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 35,
    groupId: 1,
    email: 'sposadal1@eafit.edu.co',
    name: 'SALOMÉ PAULINA POSADA LÓPEZ',
    epikId: '1002036059',
    fullName: 'SALOMÉ PAULINA POSADA LÓPEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1061265269',
    emailUppercase: 'SPOSADAL1@EAFIT.EDU.CO',
    phone: '3135792942',
    program: 'COMUNICACIÓN SOCIAL',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['PUBLICIDAD', 'RELACIONES PÚBLICAS'],
  },
  {
    id: 36,
    groupId: 1,
    email: 'fechavarriav1@eafit.edu.co',
    name: 'FELIPE ALEJANDRA ECHAVARRÍA VÁSQUEZ',
    epikId: '1007963715',
    fullName: 'FELIPE ALEJANDRA ECHAVARRÍA VÁSQUEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1060407340',
    emailUppercase: 'FECHAVARRIAV1@EAFIT.EDU.CO',
    phone: '3169576201',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 37,
    groupId: 1,
    email: 'amejiaz1@eafit.edu.co',
    name: 'ANTONIA SAMUEL MEJÍA ZAPATA',
    epikId: '1009062250',
    fullName: 'ANTONIA SAMUEL MEJÍA ZAPATA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1010814950',
    emailUppercase: 'AMEJIAZ1@EAFIT.EDU.CO',
    phone: '3137144504',
    program: 'INGENIERÍA DE PROCESOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 38,
    groupId: 1,
    email: 'dquinterol1@eafit.edu.co',
    name: 'DANIELA QUINTERO LÓPEZ',
    epikId: '1007048838',
    fullName: 'DANIELA QUINTERO LÓPEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1052274692',
    emailUppercase: 'DQUINTEROL1@EAFIT.EDU.CO',
    phone: '3105243068',
    program: 'CIENCIAS POLÍTICAS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 39,
    groupId: 1,
    email: 'eescobari1@eafit.edu.co',
    name: 'EMMANUEL ESCOBAR ISAZA',
    epikId: '1008191131',
    fullName: 'EMMANUEL ESCOBAR ISAZA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1029450273',
    emailUppercase: 'EESCOBARI1@EAFIT.EDU.CO',
    phone: '3173265515',
    program: 'DERECHO',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 40,
    groupId: 1,
    email: 'dtorresl1@eafit.edu.co',
    name: 'DAVID TORRES LONDOÑO',
    epikId: '1006610562',
    fullName: 'DAVID TORRES LONDOÑO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1079442503',
    emailUppercase: 'DTORRESL1@EAFIT.EDU.CO',
    phone: '3107275151',
    program: 'INGENIERÍA MECÁNICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 41,
    groupId: 1,
    email: 'mgiraldoc1@eafit.edu.co',
    name: 'MIGUEL ANA GIRALDO CARDONA',
    epikId: '1006360682',
    fullName: 'MIGUEL ANA GIRALDO CARDONA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1037346970',
    emailUppercase: 'MGIRALDOC1@EAFIT.EDU.CO',
    phone: '3213162947',
    program: 'INGENIERÍA DE DISEÑO DE PRODUCTO',
    secondProgram: '',
    membershipStatus: ['LICENCIA', 'ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 42,
    groupId: 1,
    email: 'smartinezr1@eafit.edu.co',
    name: 'SIMÓN MARTÍNEZ RODRÍGUEZ',
    epikId: '1003344717',
    fullName: 'SIMÓN MARTÍNEZ RODRÍGUEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1002735359',
    emailUppercase: 'SMARTINEZR1@EAFIT.EDU.CO',
    phone: '3140904824',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 43,
    groupId: 1,
    email: 'mramirezv1@eafit.edu.co',
    name: 'MANUELA IGNACIO RAMÍREZ VÁSQUEZ',
    epikId: '1001813596',
    fullName: 'MANUELA IGNACIO RAMÍREZ VÁSQUEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1077669750',
    emailUppercase: 'MRAMIREZV1@EAFIT.EDU.CO',
    phone: '3106892998',
    program: 'ADMINISTRACIÓN DE NEGOCIOS',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 44,
    groupId: 1,
    email: 'vmejiah1@eafit.edu.co',
    name: 'VERÓNICA MEJÍA HERNÁNDEZ',
    epikId: '1005059717',
    fullName: 'VERÓNICA MEJÍA HERNÁNDEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1091839693',
    emailUppercase: 'VMEJIAH1@EAFIT.EDU.CO',
    phone: '3132495470',
    program: 'CIENCIAS POLÍTICAS',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['DIVULGACIÓN'],
  },
  {
    id: 45,
    groupId: 1,
    email: 'fgomezq1@eafit.edu.co',
    name: 'FELIPE GÓMEZ QUINTERO',
    epikId: '1001770648',
    fullName: 'FELIPE GÓMEZ QUINTERO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1058186525',
    emailUppercase: 'FGOMEZQ1@EAFIT.EDU.CO',
    phone: '3197224110',
    program: 'DISEÑO INTERACTIVO',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 46,
    groupId: 1,
    email: 'cescobara1@eafit.edu.co',
    name: 'CAROLINA ESCOBAR AGUDELO',
    epikId: '1009940074',
    fullName: 'CAROLINA ESCOBAR AGUDELO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1036023439',
    emailUppercase: 'CESCOBARA1@EAFIT.EDU.CO',
    phone: '3186517976',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 47,
    groupId: 1,
    email: 'ebetancurc1@eafit.edu.co',
    name: 'ESTEBAN BETANCUR CARDONA',
    epikId: '1005452832',
    fullName: 'ESTEBAN BETANCUR CARDONA',
    documentType: 'Tarjeta de identidad',
    documentNumber: '1024406132',
    emailUppercase: 'EBETANCURC1@EAFIT.EDU.CO',
    phone: '3230875689',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS', 'PUBLICIDAD'],
  },
  {
    id: 48,
    groupId: 1,
    email: 'srestrepog1@eafit.edu.co',
    name: 'SANTIAGO RESTREPO GONZÁLEZ',
    epikId: '1006818732',
    fullName: 'SANTIAGO RESTREPO GONZÁLEZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1065575808',
    emailUppercase: 'SRESTREPOG1@EAFIT.EDU.CO',
    phone: '3249028978',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['ACTIVO', 'MIEMBRO DE JUNTA'],
    areas: [],
  },
  {
    id: 49,
    groupId: 1,
    email: 'smorenoh1@eafit.edu.co',
    name: 'SAMUEL SARA MORENO HOYOS',
    epikId: '1009285735',
    fullName: 'SAMUEL SARA MORENO HOYOS',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1071259135',
    emailUppercase: 'SMORENOH1@EAFIT.EDU.CO',
    phone: '3192276672',
    program: 'DERECHO',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 50,
    groupId: 1,
    email: 'grestrepog1@eafit.edu.co',
    name: 'GABRIELA CAMILA RESTREPO GIRALDO',
    epikId: '1008990305',
    fullName: 'GABRIELA CAMILA RESTREPO GIRALDO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1092632184',
    emailUppercase: 'GRESTREPOG1@EAFIT.EDU.CO',
    phone: '3149700783',
    program: 'INGENIERÍA MATEMÁTICA',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 51,
    groupId: 1,
    email: 'aalvarezo1@eafit.edu.co',
    name: 'ANDRÉS ÁLVAREZ OSPINA',
    epikId: '1005071208',
    fullName: 'ANDRÉS ÁLVAREZ OSPINA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1001898961',
    emailUppercase: 'AALVAREZO1@EAFIT.EDU.CO',
    phone: '3243380797',
    program: 'INGENIERÍA DE PROCESOS',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 52,
    groupId: 1,
    email: 'lgallegoa1@eafit.edu.co',
    name: 'LUCÍA SANTIAGO GALLEGO ÁLVAREZ',
    epikId: '1007389840',
    fullName: 'LUCÍA SANTIAGO GALLEGO ÁLVAREZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1045728776',
    emailUppercase: 'LGALLEGOA1@EAFIT.EDU.CO',
    phone: '3149489745',
    program: 'INGENIERÍA CIVIL',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 53,
    groupId: 1,
    email: 'slopezf1@eafit.edu.co',
    name: 'SEBASTIÁN LÓPEZ FLÓREZ',
    epikId: '1009442881',
    fullName: 'SEBASTIÁN LÓPEZ FLÓREZ',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1040780112',
    emailUppercase: 'SLOPEZF1@EAFIT.EDU.CO',
    phone: '3122865574',
    program: 'INGENIERÍA ADMINISTRATIVA',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 54,
    groupId: 1,
    email: 'pmorenoh1@eafit.edu.co',
    name: 'PAULINA MARTÍN MORENO HOYOS',
    epikId: '1005123430',
    fullName: 'PAULINA MARTÍN MORENO HOYOS',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1076320155',
    emailUppercase: 'PMORENOH1@EAFIT.EDU.CO',
    phone: '3116167949',
    program: 'MERCADEO',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['GESTIÓN HUMANA'],
  },
  {
    id: 55,
    groupId: 1,
    email: 'tvasquezm1@eafit.edu.co',
    name: 'TOMÁS VÁSQUEZ MEJÍA',
    epikId: '1001259379',
    fullName: 'TOMÁS VÁSQUEZ MEJÍA',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1021009452',
    emailUppercase: 'TVASQUEZM1@EAFIT.EDU.CO',
    phone: '3100718259',
    program: 'DERECHO',
    secondProgram: '',
    membershipStatus: ['LICENCIA'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 56,
    groupId: 1,
    email: 'amontoyah1@eafit.edu.co',
    name: 'ANA SIMÓN MONTOYA HOYOS',
    epikId: '1003318855',
    fullName: 'ANA SIMÓN MONTOYA HOYOS',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1057061186',
    emailUppercase: 'AMONTOYAH1@EAFIT.EDU.CO',
    phone: '3130810028',
    program: 'GEOLOGÍA',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['DIVULGACIÓN', 'PUBLICIDAD'],
  },
  {
    id: 57,
    groupId: 1,
    email: 'disazag1@eafit.edu.co',
    name: 'DAVID ISAZA GALLEGO',
    epikId: '1007367772',
    fullName: 'DAVID ISAZA GALLEGO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1016690465',
    emailUppercase: 'DISAZAG1@EAFIT.EDU.CO',
    phone: '3225815152',
    program: 'LITERATURA',
    secondProgram: '',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['PUBLICIDAD'],
  },
  {
    id: 58,
    groupId: 1,
    email: 'mvelezg1@eafit.edu.co',
    name: 'MARTÍN JUAN VÉLEZ GIRALDO',
    epikId: '1000433940',
    fullName: 'MARTÍN JUAN VÉLEZ GIRALDO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1012257687',
    emailUppercase: 'MVELEZG1@EAFIT.EDU.CO',
    phone: '3161451429',
    program: 'MÚSICA',
    secondProgram: '',
    membershipStatus: ['HONORARIO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 59,
    groupId: 1,
    email: 'eagudelod1@eafit.edu.co',
    name: 'ESTEBAN SOFÍA AGUDELO DUQUE',
    epikId: '1004666692',
    fullName: 'ESTEBAN SOFÍA AGUDELO DUQUE',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1024359060',
    emailUppercase: 'EAGUDELOD1@EAFIT.EDU.CO',
    phone: '3217006984',
    program: 'DISEÑO INTERACTIVO',
    secondProgram: '',
    membershipStatus: ['ACTIVO'],
    areas: ['RELACIONES PÚBLICAS'],
  },
  {
    id: 60,
    groupId: 1,
    email: 'acardonaq1@eafit.edu.co',
    name: 'ANDRÉS CARDONA QUINTERO',
    epikId: '1004835492',
    fullName: 'ANDRÉS CARDONA QUINTERO',
    documentType: 'Cédula de ciudadanía',
    documentNumber: '1088930456',
    emailUppercase: 'ACARDONAQ1@EAFIT.EDU.CO',
    phone: '3207495582',
    program: 'GEOLOGÍA',
    secondProgram: 'INGENIERÍA MECÁNICA',
    membershipStatus: ['PERÍODO DE PRUEBA'],
    areas: ['PUBLICIDAD'],
  },
];
